authentication/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from authentication.views import signaction

app_name="signupapp"
urlpatterns = [
    path('',signaction, name="signup"),
]

booking_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from booking_page.views import bookingaction

app_name="bookingapp"
urlpatterns = [
    path('',bookingaction, name="booking"),
]

hotel_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include('landing_page.urls')),
    path('admin/', admin.site.urls),
    path('signup/',include('authentication.urls')),
    path('login/',include('login_page.urls')),
    path('profile/',include('profile_page.urls')),
    path('booking/',include('booking_page.urls')),
    path('payment/',include('payment_page.urls')),
]

landing_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from landing_page.views import landingaction

app_name="landingapp"
urlpatterns = [
    path('',landingaction, name="landing"),
]

login_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from login_page.views import login_action,logout_action

app_name="loginapp"
urlpatterns = [
    path('',login_action, name="login"),
    path('logout/',logout_action, name="logout"),
    
]

payment_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from payment_page.views import pay_action

app_name="paymentapp"
urlpatterns = [
    path('',pay_action, name="pay"),
    
]

profile_page/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from profile_page.views import profile_action

app_name="profileapp"
urlpatterns = [
    path('',profile_action, name="profile_"),
]

authentication/models.py
from django.db import models

class hotelusers(models.Model):
    username = models.CharField(max_length=50, default='',null=True)
    email = models.EmailField(max_length=50, null=True)
    password = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.username

booking_page/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models

# Create your models here.

login_page/models.py
from django.db import models

# Create your models here.

payment_page/models.py
from django.db import models

# Create your models here.

profile_page/models.py
from django.db import models

# Create your models here.

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import *

def signaction(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        email=request.POST.get('email')
        password=request.POST.get('password')
        ob1=hotelusers()
        ob1.username=username
        ob1.email=email
        ob1.password=password
        ob1.save()
        return render(request,"login_.html")
    else:
        return render(request, 'signup.html')

booking_page/views.py
from django.shortcuts import render

# Create your views here.
def bookingaction(requests):
    return render(requests,'booking.html')

landing_page/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
def landingaction(request):
    return render(request,'landing.html')

login_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from authentication.models import *
from django.contrib.auth.decorators import login_required


def login_action(request):
    if request.method == 'POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=hotelusers.objects.filter(username=username,password=password)
        if user:
            return redirect('{% url "profileapp:profile_" %}')
            # return render(request,'profile.html')
        else:
            return render(request,'error.html')
    else:
        return render(request,'login_.html')

def logout_action(request):
    logout(request)
    return redirect('landing.html') 

payment_page/views.py
from django.shortcuts import render

# Create your views here.
def pay_action(requests):
    return render(requests,'payment.html')

profile_page/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from authentication.models import *
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required (login_url="login_.html")
def profile_action(request):
    #user = request.user
    #user_data = hotelusers.objects.filter(username=user)
    #context = {'user_data': user_data}
    context={}
    context['dataset'] = hotelusers.objects.all()
    return render(request, 'profile.html', context)
    # context["dataset"] = hotelusers.objects.all()

authentication/templates/signup.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="D:\SE_project\authentication\templates\authenticate.css">
    <title>Sign up</title>
</head>
<body>
    <div class="bg-image"></div>
    <div class="wrapper" id="wrap">
        <div class="form-container sign-up">
            <form action="#" method="POST">
                {% csrf_token %}
                <h2>Sign up</h2>
                <div class="form-group">
                    <input type="text" name="username" placeholder="Enter Username" required>
                    
                </div>
                <div class="form-group">
                    <input type="email" name="email" placeholder="Enter email"  required>
                </div>
                <div class="form-group">
                    <input type="password" name="password" placeholder="Enter password"  required>
                </div>
                <div class="form-group">
                    <input type="password" name="confirm_password" placeholder="Enter confirm password" required>
                </div>
                <button type="submit" class="btn" name="register">Sign up</button>
                <div class="link">
                    <p>You already have an account?<a href="{% url 'loginapp:login' %}" class="signin-link"> Sign in</a></p>
                </div>
            </form>
        </div>
    </div>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@200;400&display=swap');
*{
    margin:0;
    padding:0;
    box-sizing:border-box;  
    font-family: Noto Serif Traditional Chinese,serif;
}
html {
    font-size: 62.5%;
    scroll-behavior: smooth;
}
body {
    background-image: url("https://www.kayak.co.in/rimg/himg/76/d6/8d/hotelsdotcom-547627-b038da-123843.jpg?width=1366&height=768&crop=true");
    background-repeat: no-repeat;
    background-size: cover;
    -webkit-backdrop-filter: blur(2.5px);
    backdrop-filter: blur(2.5px);
    font-weight: 400;
    min-height: 100vh;
    display: grid;
    place-content: center;
    overflow: hidden;
}
.wrapper {
    position: relative;
    width: 35rem;
    height: 50rem;  
}
.wrapper .form-container {
    position: absolute;
    top: 0;
    left: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    height: 100%;
    background-color: #ffffff;
    border-radius: .5rem;
    box-shadow: 0 0 1rem 0 rgba(0, 0, 0, 0.2);
    border: px solid rgba(255, 255, 255, .25);
    border-radius: 20px;
    background: linear-gradient(
      120deg,
      rgba(255, 255, 255, .25),
      rgba(255, 255, 255, .75), 70%, 
      rgba(255, 255, 255, .25)
    );
    backdrop-filter: blur(25px);
}
@media(min-width:540px){
    .wrapper{
        width: 40rem;
    }
}
@media(max-width:540px)
{
    body
    {
        background-image: none;
    }
    .wrapper .form-container
    {
        border: 2px solid #0d0261;
    }

}
.wrapper .form-container form h2 {
    font-size: 3rem;
    text-align: center;
    text-transform: capitalize;
    color:#555555;
}

.wrapper .form-container form .form-group {
    position: relative;
    width: 32rem;
    margin: 3rem 0;
}
.wrapper .form-container form .form-group label {
    position: absolute;
    top: 50%;
    transform: translateY(-50%);
    font-size: 1.6rem;
    text-transform: capitalize;
    color:#333333;
    padding: 0 .5rem;
    pointer-events: none;
    transition: all .5s ease;
}

.wrapper .form-container form .form-group label {
    left: 2rem
}

.wrapper .form-container form .form-group input {
    width: 100%;
    height: 4rem;
    padding: 0 1rem;
    border-radius: .5rem;
    border: none;
    outline: none;
    border: .1rem solid #333333;
    font-size: 1.6rem;
    color: #555555;
}

form .form-group input:focus~label
{
    top: 0 !important;
    font-size: 1.2rem !important;
    background-color:#ffffff;
}

.wrapper .form-container form .forgot-pass {
    margin: -1.5rem 0 1.5rem;
}
.wrapper .form-container form .forgot-pass a {

    text-decoration: none;
    font-size: 1.4rem;
    color:#3A9DE1;
}
.wrapper .form-container form .forgot-pass a:hover {
    color:#401CDB;  
}
.wrapper .form-container form .btn {
    color:#ffffff;
    width: 100%;
    height: 4rem;
    font-size: 1.6rem;
    font-weight: 500;
    outline: none;
    border: none;
    border-radius: .5rem;
    cursor: pointer;
    box-shadow: 0 .2rem 1rem rgba(0, 0, 0, 0.4);
  
}

.wrapper .form-container form .link {
    text-align: center;
    font-size: 1.4rem;
    color:#333333;
    margin: 2.5rem 0;
}

.wrapper .form-container form .link a {
    text-decoration: none;
    font-weight: 600;
    transition: all .5s ease;
    color:#3A9DE1;
}

.wrapper .form-container form .link a:hover {
    color:#401CDB;
}

button{
    background-color: #3A9DE1;
}

</style>

booking_page/templates/booking.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" id="ic" href="https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8SG90ZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1000&q=60"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'booking.css' %}">
    <title>Booking</title>
  </head>
  <body>
    <div class="Title">
      <h1>Galaxy Hotels</h1>
      <h3>Saravanamapatty, Coimbatore &nbsp;&nbsp;&nbsp;&nbsp;Contact: 998877665423</h3>
      <h3>Exotic Amenities &nbsp;&nbsp;&nbsp; Spa  &nbsp;&nbsp;&nbsp; Multi-Cuisine Restaurant  &nbsp;&nbsp;&nbsp;  Swimming Pool &nbsp;&nbsp;&nbsp;  Service Request</h3>
    </div>
    <div class="details">
      <div class="date">
          <h2>Dates</h2>
          <div class="check-in">
          <h4>Check in : </h4>
          <input type="date" id="in" name="datein">
          </div>
          <div class="check-out">
          <h4>Check out : </h4>
          <input type="date" id="out" name="dateout">
          </div>
      </div>
      <div class="room">
        <h2>Guests</h2>
        <div class="r">
        <label for="Rooms">Rooms :</label>
        <select name="number" id="count1">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        </div>
        <div class="a">
        <label for="Adults">Adults :</label>
        <select name="number" id="count2">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        </div>
        <div class="c">
        <label for="Children">Children :</label>
          <select name="number" id="count2">
          <option value="1">1</option>
          <option value="2">2</option>
          <option value="3">3</option>
          <option value="4">4</option>
          <option value="5">5</option>
        </select>
        </div>
      </div>
    </div>
    <div class="book">
      <div class="deluxe-room">
        <h3>Deluxe Room</h3>
        <div class="dr">
          <img src="https://cache.marriott.com/marriottassets/marriott/CJBMD/cjbmd-bedroom-8458-hor-clsc.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=512px:342px">
          <div class="rates">
            <div class="r1">
              <h4>Price per night : </h4><h4>5900</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
            <div class="r2">
              <h4>Price per day : </h4><h4>7000</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
          </div>
        </div>
      </div>
      <div class="premier-room">
        <h3>Premier Room</h3>
        <div class="pr">
          <img src="https://cache.marriott.com/marriottassets/marriott/CJBMD/cjbmd-executive-suite-4803-hor-clsc.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=512px:342px">
          <div class="rates">
            <div class="r1">
              <h4>Price per night : </h4><h4>7900</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
            <div class="r2">
              <h4>Price per day : </h4><h4>9000</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
          </div>
        </div>
      </div>
      <div class="suite-room">
        <h3>Suite Room</h3>
        <div class="sr">
          <img src="https://cache.marriott.com/marriottassets/marriott/CJBMD/cjbmd-suite-8462-ver-clsc.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=512px:342px">
          <div class="rates">
            <div class="r1">
              <h4>Price per night : </h4><h4>10500</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
            <div class="r2">
              <h4>Price per day : </h4><h4>12000</h4>
              <button type="submit"><a href="{% url 'paymentapp:pay' %}">Book now</a></button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>

landing_page/templates/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="icon" type="image/svg+xml" id="ic" href="https://images.unsplash.com/photo-1584132967334-10e028bd69f7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8SG90ZWxzfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=1000&q=60" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'landing.css' %}">
    <script src="https://kit.fontawesome.com/3bc3de250b.js" crossorigin="anonymous"></script>
    <title>SH Hotels</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.css"/>
  </head>
  <body>
    <div class="sidebar" id="mysidebar">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#description" class="about_us">About Us</a>
  <a href="#rooms" class="room">Rooms</a>
  <a href="#dining" class="dine">Dining</a>
  <a href="#salon" class="spa">Salon</a>
  <a href="#contain" class="contact">Contact</a>
</div>

    <div class="outer">
      <div class="navbar">
         <div class="title">
          <div class="menu">
            <span style="font-size:25px;cursor:pointer;" onclick="openNav()">&#9776;</span>
          </div>
          <div class="heading">
          <h1>GALAXY Hotels</h1>
          </div>
        <div class="button">
           {% if user.is_authenticated %}
           <div class="L">
              <button type="button" class="login"><a href="{% url 'loginapp:logout' %}"><h5>Logout</h5></button>
          </div>
          {% else %}
          <div class="S">
               <button type="button" class="signup"><a href="{% url 'signupapp:signup' %}"><h5>Signup</h5></a></button>
          </div>
          {% endif %}
          </div>
        </div>
      </div>
     </div>
      <div class="container">
      <div class="swiper">
        <div class="swiper-wrapper">
          <div class="swiper-slide"><img src="https://images.unsplash.com/photo-1564501049412-61c2a3083791?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fEhvdGVsc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=1000&q=60" alt="Pic1"> </div>
          <div class="swiper-slide"><img src="https://images.unsplash.com/photo-1590447158019-883d8d5f8bc7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fEhvdGVsc3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=1000&q=60" alt="Pic2"> </div>
          <div class="swiper-slide"><img src="https://www.theparkhotels.com/images/site-specific/new-delhi/dining/dining_banner.jpg" alt="Pic3"> </div>  
        </div>
        <div class="swiper-pagination"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-button-next"></div>
      </div>
      </div>
  <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
  <script>const swiper = new Swiper('.swiper', {
    autoplay:
    {delay:2000,
      disableOnInteraction:false,
    },
    loop: true,
    pagination: {
      el: '.swiper-pagination',
      clickable:true,
    },
   navigation: {
      nextEl: '.swiper-button-next',
      prevEl: '.swiper-button-prev',
    },
  });</script>
  <br>
  <div class="content">
    <div class="description" id="description">
      <h2>ABOUT US</h2>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
        magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
        id dicta officia libero harum. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel iure fugiat, 
        ut vitae unde incidunt laudantium obcaecati, veritatis illo dolores rem provident qui quasi. In autem
         earum voluptates similique error? Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vel iure fugiat, 
         ut vitae unde incidunt laudantium obcaecati, veritatis illo dolores rem provident qui quasi. In autem
          earum voluptates similique error?</p>
    </div>
    <h1>ROOMS</h1>
    <hr>
    <div class="rooms" id="rooms">
      <div class="img1">
        <img src="https://dibai-7-star-hotel-nanning.booked.net/data/Photos/OriginalPhoto/8188/818841/818841098/Dibai-7-Star-Hotel-Nanning-Exterior.JPEG" alt="img1">
        <h3 class="text">Deluxe Room</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      <div class="img2">
        <img src="https://www.orientrailjourneys.com/blog/wp-content/uploads/2019/05/Pangu-Seven-Star-Hotel-China-Premier-Junior-Suite.jpg" alt="img2">
        <h3 class="text">Premier Room</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      <div class="img3">
        <img src="https://www.luxurytravelmagazine.com/files/610/1/1911/n-Royal-Suite-Bedroom_big(1)_big_bu.jpg" alt="img3">
        <h3 class="text">Suite</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
    </div>
    <button type="button" class="book"><a href="{% url 'bookingapp:booking' %}">Book Now</a></button>
    <h1>DINING</h1>
    <hr>
    <div class="dining" id="dining">
      <div class="img1">
        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrcVpcnRfcgeBEWKObLXDGHZxKFoTW03Tuzg&usqp=CAU" alt="img1">
        <h3 class="text">Asian Cuisine</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      <div class="img2">
        <img src="https://images.squarespace-cdn.com/content/v1/58363e4f15d5db57b198bfeb/1549387763673-PLYQ1HKTLJOJ0QT2OOWZ/Flavors+of+Paris+restaurant.jpg?format=2500w" alt="img2">
        <h3 class="text">Italian Cuisine</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      <div class="img3">
        <img src="https://static-ssl.businessinsider.com/image/55ba73262acae732118bb6fa-4256-2128/ristorante-la-sponda.jpg" alt="img3">
        <h3 class="text">French Cuisine</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
    </div>
   <br>
   <br>
   <br>
   <h1>Elysium Spa</h1>
   <hr>
    <div class="salon" id="salon">
      <div class="img1">
        <img src="https://warrentricomi.in/wp-content/uploads/2017/01/HealthBeauty_WarrenTricomi_SlideshowGallery_Feature_1-1.jpg" alt="img1">
        <h3 class="text">Salon</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      <div class="img2">
        <img src="https://dynamic-media-cdn.tripadvisor.com/media/photo-o/22/ff/d8/5f/lagoon-sunset-rooftop.jpg?w=700&h=-1&s=1" alt="img2">
        <h3 class="text">Spa</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet, illum corporis! Distinctio 
          magnam, atque consectetur consequuntur tempora explicabo eius laborum ipsum corporis? Officiis nulla error 
          id dicta officia libero harum.</p>
      </div>
      </div>
    </div>
  </div>
  <div class="contain" id="contain">
    <div class="container1">
        <div class="inner1">
              <h1>CONTACT US</h1>
      </div>
      <div class="inner3">
        <div class="contactus">
          <div class="flex">
          <div class="icon">
          <i class="fa-solid fa-phone fa-xl " style="color: #000000;"></i>
        </div>
        <div class="context">
          <h4>9876543210</h4>
        </div>
      </div>
        </div>
        <div class="contactus">
          <div class="flex">
          <div class="icon">
          <i class="fa-solid fa-envelope fa-xl" style="color: #000000;"></i>
        </div>
        <div class="context">
          <a href="#">www.galaxyhotels.com</a>
        </div>
      </div>
        </div>
      </div>
    </div>
   <div class="container2">
      <div class="contactus">
        <div class="flex">
        <div class="icon">
        <i class="fa-brands fa-instagram fa-xl"></i>
        </div>
        <div class="context">
        <a href="https://www.instagram.com/kct_84" target="blank">@galaxyhotels</a>
        </div>
      </div>
      </div>
    </div>
   
  
  </body>

<script>
function openNav() {
  document.getElementById("mysidebar").style.width = "200px";
}

function closeNav() {
  document.getElementById("mysidebar").style.width = "0";
}
</script>
</html>

login_page/templates/error.html
<html>
    <head>
        <title>Error page</title>
        <style>
            body{
                color: red;
                background-color: white;
                font-size: 30px;
            }
        </style>
    </head>
    <body>
        <center><h1>Invalid Entry(-_-)!</h1></center>
    </body>
</html>

profile_page/templates/profile.html
<html>
    <head>
        <title>Profile</title>
        <style>
            body{
                background-color: black;
                color: blue;
                font-size: 30px;
            }
        </style>
    </head>
    <body>
        <center><h1>Profile :-)</h1></center>
        <div class="con">
            {% for data in dataset %}.
            <p>username : {{ data.username }}</p><br/>
            <p>email : {{ data.email }}</p><br/>
            <hr/>
            {% endfor %}
        </div>
        <form action="{% url 'landingapp:landing' %}" method="POST">
        {% csrf_token %}
        <button type="submit" name="logout"><a href="{% url 'landingapp:landing' %}">LOGOUT</a></button>
        </form>
    </body>

</html>
<style>
    .con{
        color:white;
    }
</style>